# Generated by Django 4.2 on 2025-09-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('unit', models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('u', 'Unidades'), ('cup', 'Tazas'), ('tbsp', 'Cucharadas'), ('tsp', 'Cucharaditas')], max_length=10, verbose_name='Unidad')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Costo por unidad de medida especificada', max_digits=10, verbose_name='Costo por unidad')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad disponible en inventario', max_digits=10, verbose_name='Stock actual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la receta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('yield_portions', models.PositiveIntegerField(help_text='Número de porciones que produce esta receta', verbose_name='Porciones que rinde')),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de preparación (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Cantidad necesaria del ingrediente', max_digits=10, verbose_name='Cantidad')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.ingredient', verbose_name='Ingrediente')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.recipe', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
